version: '2.13'
services:
  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
    command: node dist/apps/auth/main
    # env_file:
    #   - ./apps/booking/.env
    ports:
      - '10001:10001'
  booking:
    build: 
      context: .
      dockerfile: ./apps/booking/Dockerfile
    command: npx nest start booking
    # env_file:
    #   - ./apps/booking/.env
    ports:
      - '10002:10002'
  rental:
    build: 
      context: .
      dockerfile: ./apps/rental/Dockerfile
    command: npx nest start rental
    # env_file:
    #   - ./apps/booking/.env
    ports:
      - '10003:10003'
  search:
    build: 
      context: .
      dockerfile: ./apps/search/Dockerfile
    command: npx nest start search
    # env_file:
    #   - ./apps/booking/.env
    ports:
      - '10004:10004'
