services:
  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
    command: npx prisma db pull &&  npx prisma generate && npx nest start auth
    # env_file:
    #   - ./apps/booking/.env
    ports:
      - '10001:10001'
    volumes:
      - .:/usr/src/app  
  booking:
    build: 
      context: .
      dockerfile: ./apps/booking/Dockerfile
    command: npx nest start booking
    # env_file:
    #   - ./apps/booking/.env
    ports:
      - '10002:10002'
    volumes:
      - .:/usr/src/app  
  rental:
    build: 
      context: .
      dockerfile: ./apps/rental/Dockerfile
    command: npx nest start rental
    # env_file:
    #   - ./apps/booking/.env
    ports:
      - '10003:10003'
    volumes:
      - .:/usr/src/app  
  search:
    build: 
      context: .
      dockerfile: ./apps/search/Dockerfile
    command: npx nest start search
    # env_file:
    #   - ./apps/booking/.env
    ports:
      - '10004:10004'
    volumes:
      - .:/usr/src/app  
