# This is a basic workflow that is manually triggered

name: deploy to remote server 

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    tags:
      - v*
jobs:
  execute_ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Pulling ssh action
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        password: ${{ secrets.PASS }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
          echo "Running commands!!!"
          rm -rf EjareChi_backend
          git clone https://github.com/Moeinmn/EjareChi_backend.git
          cd EjareChi_backend
          docker-compose up
